### ISSUE TITLE
Switching from Week view to Day view

### ISSUE THREAD

**Issue by hami-sh** [werner-scholtz/kalender#28] opened 2024-02-17 11:48 UTC
Hey, great widget, love how customisable it is!

I have the example code running on my phone and the browser. When I switch from Week view to Day view, the correct day number is loaded however the _previous_ day's events are shown until i swipe away to the next day, when it is properly set. 

This happens as well in my own code! Calling `setState` doesnt help.

Could you try and fix this in the next version, or show me whats wrong and I can fix it?

**Comment by werner-scholtz** [comment] 2024-02-17 13:29
Hi, I remember in the development of the package I had a few issues like that not sure what is happening, are you able to replicate it on the web demo here https://werner-scholtz.github.io/kalender/ ?

**Comment by hami-sh** [comment] 2024-02-17 23:53
Yeah, am able to recreate it. check the video below. Its the 18th of Feb for me in Australia. When I switch from week to day view, it shows the events for the 17th of Feb, but the date in the top corner remains the same. When I then navigate to the next page, the correct events are shown and the date in the top doesnt update. 

https://github.com/werner-scholtz/kalender/assets/18391419/f441cf2e-b8e3-454f-8f2c-66d518f5a1a7

**Comment by hami-sh** [comment] 2024-02-18 00:14
Just noticed as well that on the Day view, when I use `controller.animateToDate(DateTime.now())` it goes to Saturday 17th of feb (the day before my current day)? 

Seems to be related

**Comment by hami-sh** [comment] 2024-02-18 00:17
OK -- fixed it. By using `DayConfiguration` rather than 
```
CustomMultiDayConfiguration(
      name: 'Day',
      numberOfDays: 1,
```

It works perfectly. I think you have an off-by-one error somewhere!

Thanks!

**Comment by werner-scholtz** [comment] 2024-02-19 06:48
Hi thanks for the video and info, I will investigate and resolve this asap.

**Comment by werner-scholtz** [comment] 2024-02-23 12:48
> OK -- fixed it. By using `DayConfiguration` rather than
> 
> ```
> CustomMultiDayConfiguration(
>       name: 'Day',
>       numberOfDays: 1,
> )
> ```
> 
> It works perfectly. I think you have an off-by-one error somewhere!
> 
> Thanks!

Just want to confirm that the issue is specific to using the CustomMultiDayConfiguration like this.

**Comment by werner-scholtz** [comment] 2024-03-06 07:15
I wonder if this might be related to #32

**Comment by werner-scholtz** [comment] 2024-03-14 12:38
Hi this should be fixed now.

**Closed** 2024-03-26 08:06 UTC
Labels: bug
